"""empty message

Revision ID: 4ae03aae8dcb
Revises: 9c703b7670e6
Create Date: 2024-11-28 15:04:58.632286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae03aae8dcb'
down_revision = '9c703b7670e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
