"""Add image_path to DiveSite

Revision ID: f77ad8877cbe
Revises: 4ae03aae8dcb
Create Date: 2024-11-29 14:00:05.575858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77ad8877cbe'
down_revision = '4ae03aae8dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dive_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
